index:
  path: /
  controller: App\Controller\IndexController::index
  methods: GET|POST

statistic:
  path: /statistic
  controller: App\Controller\IndexController::index
  methods: GET|POST

transfer:
  path: /{url}
  controller: App\Controller\IndexController::transfer
  methods: GET
